# Minimal in-repo CMake helpers used when QPM does not generate cmake/utils.cmake.
# Kept compatible with the RECURSE_FILES helper generated by QPM.
macro(RECURSE_FILES return_list filter)
  file(GLOB_RECURSE new_list ${filter})
  set(file_list "")
  foreach(file_path ${new_list})
    set(file_list ${file_list} ${file_path})
  endforeach()
  list(REMOVE_DUPLICATES file_list)
  set(${return_list} ${file_list})
endmacro()
